test {
  useJUnitPlatform()
}

dependencies {
  implementation project(path: ':iceberg-bundled-guava', configuration: 'shadow')
  api project(':iceberg-api')
  implementation project(':iceberg-common')
  implementation project(':iceberg-core')

  compileOnly platform(libs.azuresdk.bom)
  compileOnly "com.azure:azure-storage-file-datalake"
  compileOnly "com.azure:azure-identity"

  testImplementation project(path: ':iceberg-api', configuration: 'testArtifacts')
  testImplementation libs.esotericsoftware.kryo
  testImplementation libs.testcontainers
  testImplementation libs.mockserver.netty
  testImplementation libs.mockserver.client.java
}

sourceSets {
  integration {
    java.srcDir "$projectDir/src/integration/java"
    resources.srcDir "$projectDir/src/integration/resources"
    compileClasspath += main.output + test.output
    runtimeClasspath += main.output + test.output
  }
}

configurations {
  integrationImplementation.extendsFrom testImplementation
  integrationRuntime.extendsFrom testRuntimeOnly
}

task integrationTest(type: Test) {
  useJUnitPlatform()
  testClassesDirs = sourceSets.integration.output.classesDirs
  classpath = sourceSets.integration.runtimeClasspath
  jvmArgs += project.property('extraJvmArgs')
}
check.dependsOn integrationTest
