test {
  useJUnitPlatform()
}

dependencies {
  implementation project(':core')
  implementation project(':common')
  implementation project(path: ':bundled-guava', configuration: 'shadow')
  implementation platform(libs.jackson.bom)
  implementation libs.jackson.core
  implementation libs.jackson.databind

  runtimeOnly libs.snowflake.jdbc

  testImplementation libs.mockito.junit.jupiter
  testImplementation project(path: ':core', configuration: 'testArtifacts')
}
