test {
  useJUnitPlatform()
}

dependencies {
  implementation project(':iceberg-core')
  implementation project(':iceberg-common')
  implementation project(path: ':iceberg-bundled-guava', configuration: 'shadow')
  implementation platform(libs.jackson.bom)
  implementation libs.jackson.core
  implementation libs.jackson.databind

  runtimeOnly libs.snowflake.jdbc

  testImplementation libs.mockito.junit.jupiter
  testImplementation project(path: ':iceberg-core', configuration: 'testArtifacts')
}
