test {
  useJUnitPlatform()
}
dependencies {
  implementation project(path: ':bundled-guava', configuration: 'shadow')
  api project(':api')
  implementation project(':core')
  implementation project(':common')

  implementation(libs.parquet.avro) {
    exclude group: 'org.apache.avro', module: 'avro'
    // already shaded by Parquet
    exclude group: 'it.unimi.dsi'
    exclude group: 'org.codehaus.jackson'
  }

  compileOnly libs.avro.avro
  compileOnly(libs.hadoop3.client) {
    exclude group: 'org.apache.avro', module: 'avro'
  }

  testImplementation project(path: ':api', configuration: 'testArtifacts')
  testImplementation project(path: ':core', configuration: 'testArtifacts')
}
