apply plugin: 'com.gradleup.shadow'

tasks.jar.dependsOn tasks.shadowJar

dependencies {
  compileOnly(libs.guava.guava) {
    exclude group: 'com.google.code.findbugs'
    // may be LGPL - use ALv2 findbugs-annotations instead
    exclude group: 'com.google.errorprone'
    exclude group: 'com.google.j2objc'
  }
}

shadowJar {
  archiveClassifier.set(null)
  configurations = [project.configurations.compileClasspath]
  zip64 true

  // include the LICENSE and NOTICE files for the shaded Jar
  from(projectDir) {
    include 'LICENSE'
    include 'NOTICE'
  }

  dependencies {
    exclude(dependency('org.slf4j:slf4j-api'))
    exclude(dependency('org.checkerframework:checker-qual'))
  }

  relocate 'com.google.common', 'org.apache.iceberg.relocated.com.google.common'

  minimize()
}

jar {
  archiveClassifier.set('empty')
}
