dependencies {
  implementation project(path: ':bundled-guava', configuration: 'shadow')
  api project(':api')
  implementation project(':core')
  compileOnly project(':parquet')
  compileOnly project(':orc')
  compileOnly(libs.hadoop3.common) {
    exclude group: 'commons-beanutils'
    exclude group: 'org.apache.avro', module: 'avro'
    exclude group: 'org.slf4j', module: 'slf4j-log4j12'
  }

  implementation("${libs.orc.core.get().module}:${libs.versions.orc.get()}:nohive") {
    exclude group: 'org.apache.hadoop'
    exclude group: 'commons-lang'
    // These artifacts are shaded and included in the orc-core fat jar
    exclude group: 'com.google.protobuf', module: 'protobuf-java'
    exclude group: 'org.apache.hive', module: 'hive-storage-api'
  }

  implementation(libs.parquet.avro) {
    exclude group: 'org.apache.avro', module: 'avro'
    // already shaded by Parquet
    exclude group: 'it.unimi.dsi'
    exclude group: 'org.codehaus.jackson'
  }

  compileOnly libs.avro.avro

  testImplementation(libs.hadoop3.client) {
    exclude group: 'org.apache.avro', module: 'avro'
    exclude group: 'org.slf4j', module: 'slf4j-log4j12'
  }

  testImplementation project(path: ':api', configuration: 'testArtifacts')
  testImplementation project(path: ':core', configuration: 'testArtifacts')
  testImplementation libs.junit.vintage.engine
}

test {
  useJUnitPlatform()
  // Only for TestSplitScan as of Gradle 5.0+
  maxHeapSize '1500m'
}