apply plugin: 'java-platform'
//apply plugin: 'base'

dependencies {
  constraints {
    // The Iceberg-Build builds for only one Scala version at a time, so the BOM would also
    // only contain artifacts for that single Scala version. The following code ensures that
    // the BOM references the artifacts for all Scala versions.
    def sparkScalaPattern = ~"(.*)-([0-9][.][0-9]+)_([0-9][.][0-9]+)"
    def sparkScalaVersions = [
      "3.4": ["2.12", "2.13"],
      "3.5": ["2.12", "2.13"],
    ]
    rootProject.allprojects.forEach {
      // Do not include ':spark', the bom itself and the root project.
      if (it.name != 'bom' && it != rootProject && it.childProjects.isEmpty()) {
        if (it.name.startsWith("spark-")) {
          def sparkScalaMatcher = sparkScalaPattern.matcher(it.name)
          if (!sparkScalaMatcher.find()) {
            throw new GradleException("Expected a Spark/Scala version combination in Gradle project name ${it.name}")
          }
          def prjName = sparkScalaMatcher.group(1)
          def sparkVer = sparkScalaMatcher.group(2)
          for (def scalaVer in sparkScalaVersions[sparkVer]) {
            add("api", "${it.group}:$prjName-${sparkVer}_$scalaVer:${it.version}")
          }
        } else {
          add("api", project(it.path))
        }
      }
    }
  }
}

// Needed to get the "faked" Scala artifacts into the bom
javaPlatform { allowDependencies() }
