test {
  useJUnitPlatform()
}

dependencies {
  implementation project(path: ':iceberg-bundled-guava', configuration: 'shadow')
  compileOnly libs.errorprone.annotations
  compileOnly libs.findbugs.jsr305
  testImplementation libs.avro.avro
  testImplementation libs.esotericsoftware.kryo
  testImplementation libs.awaitility
}

tasks.processTestResources.dependsOn rootProject.tasks.buildInfo

// Workaround to prevent:
// Task ':iceberg-api:processTestResources' uses this output of task
// ':spotlessInternalRegisterDependencies' without declaring an explicit or implicit dependency.
// This can lead to incorrect results being produced, depending on what order the tasks are executed.
rootProject.tasks.configureEach { rootTask ->
  if (rootTask.name == 'spotlessInternalRegisterDependencies') {
    tasks.processTestResources.dependsOn rootTask
  }
}

sourceSets {
  test {
    resources {
      srcDir "${rootDir}/build"
    }
  }
}
