apply plugin: 'java-test-fixtures'
apply plugin: 'com.gradleup.shadow'

build.dependsOn shadowJar

dependencies {
  testImplementation project(':api')
  testImplementation project(':core')
  testImplementation project(':core').sourceSets.test.runtimeClasspath
  testImplementation(testFixtures(project(':open-api')))

  testImplementation libs.junit.jupiter
  testImplementation libs.junit.suite.api
  testImplementation libs.junit.suite.engine
  testImplementation libs.assertj.core

  testImplementation project(':aws-bundle')
  testImplementation project(':gcp-bundle')
  testImplementation project(':azure-bundle')

  testFixturesImplementation project(':api')
  testFixturesImplementation project(':core')
  testFixturesImplementation project(path: ':core', configuration: 'testArtifacts')
  testFixturesImplementation project(':aws')
  testFixturesImplementation project(':gcp')
  testFixturesImplementation project(':azure')
  testFixturesImplementation(libs.hadoop3.common) {
    exclude group: 'org.slf4j'
    exclude group: 'ch.qos.reload4j'
    exclude group: 'org.apache.avro', module: 'avro'
    exclude group: 'com.google.guava'
    exclude group: 'com.google.protobuf'
    exclude group: 'org.apache.curator'
    exclude group: 'org.apache.zookeeper'
    exclude group: 'org.apache.kerby'
    exclude group: 'org.apache.hadoop.thirdparty', module: 'hadoop-shaded-protobuf_3_7'
    exclude group: 'org.eclipse.jetty'
    exclude group: 'com.google.re2j', module: 're2j'
    exclude group: 'com.google.code.gson', module: 'gson'
    exclude group: 'com.jcraft', module: 'jsch'
    exclude group: 'com.google.code.findbugs', module: 'jsr305'
    exclude group: 'io.dropwizard.metrics', module: 'metrics-core'
    exclude group: 'dnsjava', module: 'dnsjava'
    exclude group: 'org.xerial.snappy', module: 'snappy-java'
    exclude group: 'commons-cli', module: 'commons-cli'
    exclude group: 'com.github.pjfanning', module: 'jersey-json'
  }
  testFixturesImplementation project(path: ':bundled-guava', configuration: 'shadow')
  testFixturesImplementation libs.junit.jupiter

  testFixturesImplementation libs.slf4j.api
  testFixturesImplementation libs.slf4j.simple

  testFixturesImplementation libs.jetty.servlet
  testFixturesImplementation libs.jetty.server
  testFixturesImplementation libs.sqlite.jdbc

  testFixturesCompileOnly libs.apiguardian

  testFixturesRuntimeOnly project(':aws-bundle')
  testFixturesRuntimeOnly project(':azure-bundle')
  testFixturesRuntimeOnly project(':gcp-bundle')
}

test {
  useJUnitPlatform()

  // Always rerun the compatibility tests
  outputs.upToDateWhen {false}
  maxParallelForks = 1

  // Pass through any system properties that start with "rck" (REST Compatibility Kit)
  // Note: only pass through specific properties so they do not affect other build/test
  //       configurations
  systemProperties System.properties
          .findAll { k, v -> k.startsWith("rck") }
          .collectEntries { k, v -> [(k):v, (k.replaceFirst("rck.", "")):v] } // strip prefix
}

def restCatalogSpec = "$projectDir/rest-catalog-open-api.yaml"
tasks.register('validateRESTCatalogSpec', org.openapitools.generator.gradle.plugin.tasks.ValidateTask) {
  inputSpec.set(restCatalogSpec)
  recommend.set(true)
}
check.dependsOn('validateRESTCatalogSpec')

shadowJar {
  archiveBaseName.set("iceberg-open-api-test-fixtures-runtime")
  archiveClassifier.set(null)
  configurations = [project.configurations.testFixturesRuntimeClasspath]
  from sourceSets.testFixtures.output
  zip64 true

  // include the LICENSE and NOTICE files for the runtime Jar
  from(projectDir) {
    include 'LICENSE'
    include 'NOTICE'
  }

  manifest {
    attributes 'Main-Class': 'org.apache.iceberg.rest.RESTCatalogServer'
  }
}

jar {
  enabled = false
}
